### PR TITLE
Update URLs in tests

### PR DESCRIPTION
**Pull request by notZaki**
The tests have been failing recently because they need to download data but those URLs no longer work.
This PR updates the outdated URLs.

**Other changes:**

- Replaced `gunzip` with `gzip`
    + Reason: I had an easier time setting up gzip to work on windows, whereas I couldn't figure out how to install gunzip
- Removed Julia 0.7 from the travis tests since it is similar to 1.0. Added Julia 1.2 for completeness.

### CODE REVIEW

**Comment by sjkelly** [comment]
GZip change looks good.

We might just want to host the test files on GitHub or somewhere else. I think if DropBox gets weird requests it will block them.

**Comment by Tokazama** [comment]
It might be worth pulling some files from [here](https://www.nitrc.org/plugins/mwiki/index.php/dcm2nii:MainPage) (look under "Slice timing correction" for the first actual DICOM file mention). This would probably be more ambitious than what you're going for now

**Comment by sjkelly** [comment]
There are also some example DICOMS here: https://github.com/CIBC-Internal/Seg3DData/tree/cbe9eeabbfaeebdd6d05521ff31464e929491966/example_dicom

**Comment by notZaki** [comment]
Thanks for the links with the DICOM samples @sjkelly @Tokazama .
I've been wanting to extend the tests to include some files from the dcm_qa repositories [mentioned in another issue](https://github.com/JuliaIO/DICOM.jl/issues/29#issuecomment-459787056) but haven't had the time to look through them.

The current tests use a few files from [Barré's DICOM samples](https://barre.dev/medical/samples/). That website was recently updated and the sample files are now on dropbox. 
If dropbox is an issue, then the DICOM samples could be checked into this repository (adds a bit of bloat #22) or hosted in a separate repository.

I'm leaning towards the latter option of hosting them in a separate repository and I'll try doing that this week. Let me know if there's any other suggestions.

We can extend the tests as well with more DICOM samples, but I would prefer getting the current tests dealt with first.

**Comment by Tokazama** [comment]
Fixing what we have now and extending later sounds very reasonable.

**Comment by sjkelly** [comment]
Sounds good. As an aside I have been working to make isosurface extraction work better with NRRD and DICOMs in Meshing.jl. I will add a DICOM example here soon: https://juliageometry.github.io/Meshing.jl/dev/examples/#NRRD-Data-1

**Comment by notZaki** [comment]
Sounds good @sjkelly 

On my end, I made [a github repository containing the DICOM files](https://github.com/notZaki/DICOMSamples) for testing. 
The testing code was refactored a bit since we no longer have to worry about g/unzipping---this also makes it easier to test on windows.

**Comment by notZaki** [comment]
If there are no objections then I'll merge this by the end of the week.

**Pull request merged**
